version: '3.8'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - CAFETERIA_API_BASE_URL=${CAFETERIA_API_BASE_URL}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEAVIATE_HOST=${WEAVIATE_HOST}
    depends_on:
      - db
      - weaviate
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
  weaviate:
    image: semitechnologies/weaviate:1.23.7
    ports:
      - '8080:8080'
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      CLUSTER_HOSTNAME: weaviate
    volumes:
      - weaviate_data:/var/lib/weaviate
volumes:
  db_data:
  weaviate_data: 